require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe DiarioalunosController do

  # This should return the minimal set of attributes required to create a valid
  # Diarioaluno. As you add validations to Diarioaluno, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) { { "mediafinal" => "MyString" } }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # DiarioalunosController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all diarioalunos as @diarioalunos" do
      diarioaluno = Diarioaluno.create! valid_attributes
      get :index, {}, valid_session
      assigns(:diarioalunos).should eq([diarioaluno])
    end
  end

  describe "GET show" do
    it "assigns the requested diarioaluno as @diarioaluno" do
      diarioaluno = Diarioaluno.create! valid_attributes
      get :show, {:id => diarioaluno.to_param}, valid_session
      assigns(:diarioaluno).should eq(diarioaluno)
    end
  end

  describe "GET new" do
    it "assigns a new diarioaluno as @diarioaluno" do
      get :new, {}, valid_session
      assigns(:diarioaluno).should be_a_new(Diarioaluno)
    end
  end

  describe "GET edit" do
    it "assigns the requested diarioaluno as @diarioaluno" do
      diarioaluno = Diarioaluno.create! valid_attributes
      get :edit, {:id => diarioaluno.to_param}, valid_session
      assigns(:diarioaluno).should eq(diarioaluno)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Diarioaluno" do
        expect {
          post :create, {:diarioaluno => valid_attributes}, valid_session
        }.to change(Diarioaluno, :count).by(1)
      end

      it "assigns a newly created diarioaluno as @diarioaluno" do
        post :create, {:diarioaluno => valid_attributes}, valid_session
        assigns(:diarioaluno).should be_a(Diarioaluno)
        assigns(:diarioaluno).should be_persisted
      end

      it "redirects to the created diarioaluno" do
        post :create, {:diarioaluno => valid_attributes}, valid_session
        response.should redirect_to(Diarioaluno.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved diarioaluno as @diarioaluno" do
        # Trigger the behavior that occurs when invalid params are submitted
        Diarioaluno.any_instance.stub(:save).and_return(false)
        post :create, {:diarioaluno => { "mediafinal" => "invalid value" }}, valid_session
        assigns(:diarioaluno).should be_a_new(Diarioaluno)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        Diarioaluno.any_instance.stub(:save).and_return(false)
        post :create, {:diarioaluno => { "mediafinal" => "invalid value" }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested diarioaluno" do
        diarioaluno = Diarioaluno.create! valid_attributes
        # Assuming there are no other diarioalunos in the database, this
        # specifies that the Diarioaluno created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        Diarioaluno.any_instance.should_receive(:update_attributes).with({ "mediafinal" => "MyString" })
        put :update, {:id => diarioaluno.to_param, :diarioaluno => { "mediafinal" => "MyString" }}, valid_session
      end

      it "assigns the requested diarioaluno as @diarioaluno" do
        diarioaluno = Diarioaluno.create! valid_attributes
        put :update, {:id => diarioaluno.to_param, :diarioaluno => valid_attributes}, valid_session
        assigns(:diarioaluno).should eq(diarioaluno)
      end

      it "redirects to the diarioaluno" do
        diarioaluno = Diarioaluno.create! valid_attributes
        put :update, {:id => diarioaluno.to_param, :diarioaluno => valid_attributes}, valid_session
        response.should redirect_to(diarioaluno)
      end
    end

    describe "with invalid params" do
      it "assigns the diarioaluno as @diarioaluno" do
        diarioaluno = Diarioaluno.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Diarioaluno.any_instance.stub(:save).and_return(false)
        put :update, {:id => diarioaluno.to_param, :diarioaluno => { "mediafinal" => "invalid value" }}, valid_session
        assigns(:diarioaluno).should eq(diarioaluno)
      end

      it "re-renders the 'edit' template" do
        diarioaluno = Diarioaluno.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Diarioaluno.any_instance.stub(:save).and_return(false)
        put :update, {:id => diarioaluno.to_param, :diarioaluno => { "mediafinal" => "invalid value" }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested diarioaluno" do
      diarioaluno = Diarioaluno.create! valid_attributes
      expect {
        delete :destroy, {:id => diarioaluno.to_param}, valid_session
      }.to change(Diarioaluno, :count).by(-1)
    end

    it "redirects to the diarioalunos list" do
      diarioaluno = Diarioaluno.create! valid_attributes
      delete :destroy, {:id => diarioaluno.to_param}, valid_session
      response.should redirect_to(diarioalunos_url)
    end
  end

end
