require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe FrequenciasController do

  # This should return the minimal set of attributes required to create a valid
  # Frequencia. As you add validations to Frequencia, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) { { "frequencia" => "MyString" } }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # FrequenciasController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all frequencias as @frequencias" do
      frequencia = Frequencia.create! valid_attributes
      get :index, {}, valid_session
      assigns(:frequencias).should eq([frequencia])
    end
  end

  describe "GET show" do
    it "assigns the requested frequencia as @frequencia" do
      frequencia = Frequencia.create! valid_attributes
      get :show, {:id => frequencia.to_param}, valid_session
      assigns(:frequencia).should eq(frequencia)
    end
  end

  describe "GET new" do
    it "assigns a new frequencia as @frequencia" do
      get :new, {}, valid_session
      assigns(:frequencia).should be_a_new(Frequencia)
    end
  end

  describe "GET edit" do
    it "assigns the requested frequencia as @frequencia" do
      frequencia = Frequencia.create! valid_attributes
      get :edit, {:id => frequencia.to_param}, valid_session
      assigns(:frequencia).should eq(frequencia)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Frequencia" do
        expect {
          post :create, {:frequencia => valid_attributes}, valid_session
        }.to change(Frequencia, :count).by(1)
      end

      it "assigns a newly created frequencia as @frequencia" do
        post :create, {:frequencia => valid_attributes}, valid_session
        assigns(:frequencia).should be_a(Frequencia)
        assigns(:frequencia).should be_persisted
      end

      it "redirects to the created frequencia" do
        post :create, {:frequencia => valid_attributes}, valid_session
        response.should redirect_to(Frequencia.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved frequencia as @frequencia" do
        # Trigger the behavior that occurs when invalid params are submitted
        Frequencia.any_instance.stub(:save).and_return(false)
        post :create, {:frequencia => { "frequencia" => "invalid value" }}, valid_session
        assigns(:frequencia).should be_a_new(Frequencia)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        Frequencia.any_instance.stub(:save).and_return(false)
        post :create, {:frequencia => { "frequencia" => "invalid value" }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested frequencia" do
        frequencia = Frequencia.create! valid_attributes
        # Assuming there are no other frequencias in the database, this
        # specifies that the Frequencia created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        Frequencia.any_instance.should_receive(:update_attributes).with({ "frequencia" => "MyString" })
        put :update, {:id => frequencia.to_param, :frequencia => { "frequencia" => "MyString" }}, valid_session
      end

      it "assigns the requested frequencia as @frequencia" do
        frequencia = Frequencia.create! valid_attributes
        put :update, {:id => frequencia.to_param, :frequencia => valid_attributes}, valid_session
        assigns(:frequencia).should eq(frequencia)
      end

      it "redirects to the frequencia" do
        frequencia = Frequencia.create! valid_attributes
        put :update, {:id => frequencia.to_param, :frequencia => valid_attributes}, valid_session
        response.should redirect_to(frequencia)
      end
    end

    describe "with invalid params" do
      it "assigns the frequencia as @frequencia" do
        frequencia = Frequencia.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Frequencia.any_instance.stub(:save).and_return(false)
        put :update, {:id => frequencia.to_param, :frequencia => { "frequencia" => "invalid value" }}, valid_session
        assigns(:frequencia).should eq(frequencia)
      end

      it "re-renders the 'edit' template" do
        frequencia = Frequencia.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Frequencia.any_instance.stub(:save).and_return(false)
        put :update, {:id => frequencia.to_param, :frequencia => { "frequencia" => "invalid value" }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested frequencia" do
      frequencia = Frequencia.create! valid_attributes
      expect {
        delete :destroy, {:id => frequencia.to_param}, valid_session
      }.to change(Frequencia, :count).by(-1)
    end

    it "redirects to the frequencias list" do
      frequencia = Frequencia.create! valid_attributes
      delete :destroy, {:id => frequencia.to_param}, valid_session
      response.should redirect_to(frequencias_url)
    end
  end

end
