require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe MatriculadosController do

  # This should return the minimal set of attributes required to create a valid
  # Matriculado. As you add validations to Matriculado, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) { { "periodo" => "MyString" } }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # MatriculadosController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all matriculados as @matriculados" do
      matriculado = Matriculado.create! valid_attributes
      get :index, {}, valid_session
      assigns(:matriculados).should eq([matriculado])
    end
  end

  describe "GET show" do
    it "assigns the requested matriculado as @matriculado" do
      matriculado = Matriculado.create! valid_attributes
      get :show, {:id => matriculado.to_param}, valid_session
      assigns(:matriculado).should eq(matriculado)
    end
  end

  describe "GET new" do
    it "assigns a new matriculado as @matriculado" do
      get :new, {}, valid_session
      assigns(:matriculado).should be_a_new(Matriculado)
    end
  end

  describe "GET edit" do
    it "assigns the requested matriculado as @matriculado" do
      matriculado = Matriculado.create! valid_attributes
      get :edit, {:id => matriculado.to_param}, valid_session
      assigns(:matriculado).should eq(matriculado)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Matriculado" do
        expect {
          post :create, {:matriculado => valid_attributes}, valid_session
        }.to change(Matriculado, :count).by(1)
      end

      it "assigns a newly created matriculado as @matriculado" do
        post :create, {:matriculado => valid_attributes}, valid_session
        assigns(:matriculado).should be_a(Matriculado)
        assigns(:matriculado).should be_persisted
      end

      it "redirects to the created matriculado" do
        post :create, {:matriculado => valid_attributes}, valid_session
        response.should redirect_to(Matriculado.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved matriculado as @matriculado" do
        # Trigger the behavior that occurs when invalid params are submitted
        Matriculado.any_instance.stub(:save).and_return(false)
        post :create, {:matriculado => { "periodo" => "invalid value" }}, valid_session
        assigns(:matriculado).should be_a_new(Matriculado)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        Matriculado.any_instance.stub(:save).and_return(false)
        post :create, {:matriculado => { "periodo" => "invalid value" }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested matriculado" do
        matriculado = Matriculado.create! valid_attributes
        # Assuming there are no other matriculados in the database, this
        # specifies that the Matriculado created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        Matriculado.any_instance.should_receive(:update_attributes).with({ "periodo" => "MyString" })
        put :update, {:id => matriculado.to_param, :matriculado => { "periodo" => "MyString" }}, valid_session
      end

      it "assigns the requested matriculado as @matriculado" do
        matriculado = Matriculado.create! valid_attributes
        put :update, {:id => matriculado.to_param, :matriculado => valid_attributes}, valid_session
        assigns(:matriculado).should eq(matriculado)
      end

      it "redirects to the matriculado" do
        matriculado = Matriculado.create! valid_attributes
        put :update, {:id => matriculado.to_param, :matriculado => valid_attributes}, valid_session
        response.should redirect_to(matriculado)
      end
    end

    describe "with invalid params" do
      it "assigns the matriculado as @matriculado" do
        matriculado = Matriculado.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Matriculado.any_instance.stub(:save).and_return(false)
        put :update, {:id => matriculado.to_param, :matriculado => { "periodo" => "invalid value" }}, valid_session
        assigns(:matriculado).should eq(matriculado)
      end

      it "re-renders the 'edit' template" do
        matriculado = Matriculado.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Matriculado.any_instance.stub(:save).and_return(false)
        put :update, {:id => matriculado.to_param, :matriculado => { "periodo" => "invalid value" }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested matriculado" do
      matriculado = Matriculado.create! valid_attributes
      expect {
        delete :destroy, {:id => matriculado.to_param}, valid_session
      }.to change(Matriculado, :count).by(-1)
    end

    it "redirects to the matriculados list" do
      matriculado = Matriculado.create! valid_attributes
      delete :destroy, {:id => matriculado.to_param}, valid_session
      response.should redirect_to(matriculados_url)
    end
  end

end
